export const providerCatalog = [
  {
    id: "shutterstock",
    name: "Shutterstock",
    status: "image_license_ready",
    requiresApiKey: true,
    serviceType: "A2MCP",
    credentialType: "OAuth application + API subscription",
    supportedAssetTypes: ["image"],
    officialUrl: "https://www.shutterstock.com/api/pricing",
    capabilities: ["search", "platform_license", "license"],
    policy: "Use for image licensing with the proper scopes and subscription. Search works with the configured access token; licensing requires licenses.create, licenses.view and purchases.view.",
  },
  {
    id: "freesound",
    name: "Freesound",
    status: "commercial_approval_required",
    requiresApiKey: true,
    serviceType: "A2MCP",
    credentialType: "API token + optional OAuth2 app",
    supportedAssetTypes: ["sound_effect", "music"],
    officialUrl: "https://freesound.org/docs/api/",
    capabilities: ["search", "preview", "metadata"],
    policy: "Token auth is sufficient for search and previews. OAuth2 is required for uploads, ratings, bookmarks and original-file downloads. Each sound still has its own license.",
  },
  {
    id: "jamendo",
    name: "Jamendo",
    status: "commercial_api_approval_required",
    requiresApiKey: true,
    serviceType: "A2MCP",
    credentialType: "Developer client_id",
    supportedAssetTypes: ["music"],
    officialUrl: "https://developer.jamendo.com/v3.0/docs",
    capabilities: ["search", "preview", "metadata", "license_terms_capture"],
    policy: "Public catalog search uses a client_id. ZitoAI captures license/commercial handoff evidence, but does not auto-purchase Jamendo commercial licenses without a separate Jamendo agreement.",
  },
];
