export const providerCatalog = [
  {
    id: "adobe_stock",
    name: "Adobe Stock",
    status: "approval_required",
    requiresApiKey: true,
    credentialType: "OAuth or Enterprise service account",
    supportedAssetTypes: ["image", "video"],
    officialUrl: "https://developer.adobe.com/stock/docs/getting-started/",
    capabilities: ["search", "license", "signed_download"],
    policy: "Customer OAuth is safest. A company account licensing for customers requires Adobe approval/contract.",
  },
  {
    id: "motion_elements",
    name: "MotionElements",
    status: "credential_required",
    requiresApiKey: true,
    credentialType: "API secret key",
    supportedAssetTypes: ["music", "sound_effect", "image", "video"],
    officialUrl: "https://api-docs.motionelements.com/",
    capabilities: ["search", "license", "download", "license_certificate"],
    policy: "Pay-per-item purchases can change the licensee to a client once; subscriptions are single-seat.",
  },
  {
    id: "shutterstock",
    name: "Shutterstock",
    status: "free_test_images_only",
    requiresApiKey: true,
    credentialType: "OAuth application + API subscription",
    supportedAssetTypes: ["image", "video", "music"],
    officialUrl: "https://www.shutterstock.com/api/pricing",
    capabilities: ["search", "platform_license", "license"],
    policy: "Free account is image-only; Platform License does not permit standalone raw-file delivery.",
  },
  {
    id: "freesound",
    name: "Freesound",
    status: "commercial_approval_required",
    requiresApiKey: true,
    credentialType: "API client key",
    supportedAssetTypes: ["sound_effect", "music"],
    officialUrl: "https://freesound.org/docs/api/",
    capabilities: ["search", "preview", "metadata"],
    policy: "Commercial API use is negotiated case by case; individual CC licenses remain file-specific.",
  },
  {
    id: "jamendo",
    name: "Jamendo",
    status: "commercial_api_approval_required",
    requiresApiKey: true,
    credentialType: "Developer API key/OAuth",
    supportedAssetTypes: ["music"],
    officialUrl: "https://developer.jamendo.com/v3.0/docs",
    capabilities: ["search", "preview", "metadata"],
    policy: "API is free for non-commercial use; commercial API access requires a sales agreement.",
  },
  {
    id: "epidemic_sound",
    name: "Epidemic Sound",
    status: "partner_required_for_production",
    requiresApiKey: true,
    credentialType: "Partner API key",
    supportedAssetTypes: ["music", "sound_effect"],
    officialUrl: "https://www.epidemicsound.com/business/developers/",
    capabilities: ["search", "preview", "in_app_use", "license"],
    policy: "Free API tier is for prototyping/evaluation; production requires Partner API access.",
  },
  {
    id: "soundstripe",
    name: "Soundstripe",
    status: "partner_required",
    requiresApiKey: true,
    credentialType: "Partner/Enterprise credentials",
    supportedAssetTypes: ["music", "sound_effect", "video"],
    officialUrl: "https://www.soundstripe.com/api",
    capabilities: ["search", "preview", "in_app_use", "resale_by_agreement"],
    policy: "API, resale and custom distribution are partnership models; use only under signed terms.",
  },
  {
    id: "lots_of_sounds",
    name: "Lots of Sounds",
    status: "paid_api",
    requiresApiKey: true,
    credentialType: "Paid API subscription",
    supportedAssetTypes: ["sound_effect"],
    officialUrl: "https://www.lotsofsounds.com/",
    capabilities: ["search", "download"],
    policy: "Do not activate until API pricing and redistribution rights are accepted.",
  },
  {
    id: "soundsfree",
    name: "SoundsFree",
    status: "no_documented_api",
    requiresApiKey: false,
    credentialType: null,
    supportedAssetTypes: ["sound_effect", "music"],
    officialUrl: "https://www.soundsfree.art/",
    capabilities: ["browser_download"],
    policy: "No documented REST API; do not scrape. Add only after written permission or an official feed.",
  },
  {
    id: "musickits",
    name: "Musickits",
    status: "no_documented_api",
    requiresApiKey: false,
    credentialType: null,
    supportedAssetTypes: ["music"],
    officialUrl: "https://musickits.net/",
    capabilities: ["browser_download"],
    policy: "Free CC BY tracks require attribution; no documented API. Request a feed instead of scraping.",
  },
  {
    id: "creative_commons_chooser",
    name: "Creative Commons chooser",
    status: "not_a_media_provider",
    requiresApiKey: false,
    credentialType: null,
    supportedAssetTypes: ["music", "sound_effect", "image", "video"],
    officialUrl: "https://creativecommons.org/choose/",
    capabilities: ["license_selection"],
    policy: "Use as a license-selection aid, never as evidence that a particular asset is licensed.",
  },
];
