export const providerCatalog = [
  {
    id: "shutterstock",
    name: "Shutterstock",
    status: "image_license_ready",
    requiresApiKey: true,
    credentialType: "OAuth application + API subscription",
    supportedAssetTypes: ["image", "video", "music"],
    officialUrl: "https://www.shutterstock.com/api/pricing",
    capabilities: ["search", "platform_license", "license"],
    policy: "Use for image licensing with the proper scopes and subscription. Search works with the configured access token; licensing requires licenses.create, licenses.view and purchases.view.",
  },
  {
    id: "freesound",
    name: "Freesound",
    status: "commercial_approval_required",
    requiresApiKey: true,
    credentialType: "API client key",
    supportedAssetTypes: ["sound_effect", "music"],
    officialUrl: "https://freesound.org/docs/api/",
    capabilities: ["search", "preview", "metadata"],
    policy: "Commercial API use is negotiated case by case; individual CC licenses remain file-specific.",
  },
  {
    id: "jamendo",
    name: "Jamendo",
    status: "commercial_api_approval_required",
    requiresApiKey: true,
    credentialType: "Developer API key/OAuth",
    supportedAssetTypes: ["music"],
    officialUrl: "https://developer.jamendo.com/v3.0/docs",
    capabilities: ["search", "preview", "metadata"],
    policy: "API is free for non-commercial use; commercial API access requires a sales agreement.",
  },
];
